Step 8/20 : RUN conda install -c plotly plotly=4.1.0
 ---> Running in a9fdf990189e
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::matplotlib==3.1.3=py36_0
  - fastai/noarch::fastai==1.0.60=1
  - conda-forge/noarch::lunarcalendar==0.0.9=py_0
  - conda-forge/noarch::arviz==0.7.0=py_0
  - conda-forge/noarch::tsfresh==0.15.1=py_0
  - conda-forge/noarch::scikit-optimize==0.7.4=py_0
  - conda-forge/linux-64::fbprophet==0.6=py36he1b5a44_0
  - conda-forge/linux-64::scikit-multiflow==0.4.1=py36h9de70de_1
  - conda-forge/noarch::copulae==0.3.1=py_0
  - conda-forge/linux-64::statsmodels==0.11.1=py36h8c4c3a4_1
  - conda-forge/linux-64::pystan==2.19.1.1=py36hb3f55d8_1
  - conda-forge/noarch::pymc3==3.8=py_0
  - conda-forge/noarch::featuretools==0.13.4=py_0
  - defaults/noarch::smart_open==1.11.1=py_0
  - defaults/linux-64::gensim==3.8.0=py36h962f231_0
  - conda-forge/noarch::jupyterlab_server==1.1.1=py_0
  - conda-forge/noarch::jupyter_client==6.1.3=py_0
  - conda-forge/noarch::jupyterlab==2.1.0=py_1
  - conda-forge/linux-64::ipykernel==5.2.1=py36h95af2a2_0
  - conda-forge/linux-64::notebook==6.0.3=py36_0
  - defaults/linux-64::blaze==0.11.3=py36_0
  - defaults/linux-64::bokeh==2.0.2=py36_0
  - defaults/noarch::xarray==0.15.1=py_0
  - defaults/noarch::dask==2.15.0=py_0
  - defaults/linux-64::distributed==2.15.2=py36_0
  - defaults/linux-64::datashape==0.5.4=py36_1
  - defaults/linux-64::pandas==0.25.3=py36he6710b0_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
